[package]
name = "shader-glam"
version = "0.1.0"
edition = "2021"

[features]
default = ["glam"]
glam = ["dep:glam"]
spirv-std = ["dep:spirv-std"]

[dependencies]
glam = { version = "0.23.0", optional = true }
spirv-std = { version = "0.5.0", optional = true }
