[package]
name = "viewer"
version = "0.1.0"
edition = "2021"

[features]
default = []
webgl = []

[dependencies]
bevy = "0.9.1"
bevy-rust-gpu = { path = "../bevy-rust-gpu" }
shader-util = { path = "../../../shared/shader-util" }
