[package]
name = "viewer"
version = "0.1.0"
edition = "2021"

[features]
default = ["shader-meta", "entry-point-export"]
shader-meta = ["bevy-rust-gpu/shader-meta"]
entry-point-export = ["bevy-rust-gpu/entry-point-export"]
webgl = []

[dependencies]
bevy = "0.9.1"
bevy_mod_debugdump = "0.6.0"
bevy-rust-gpu = "0.1.0"
shader-util = "0.1.0"
