[package]
name = "bevy-pbr-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "1.3.2"
spirv-std = "0.5.0"
shader-util = { path = "../shader-util", default-features = false, features = ["spirv-std"] }
