[workspace]
resolver = "2"
members = [
    "crates/bevy-pbr-rust",
    "crates/bevy-rust-gpu-macros",
    "crates/shader",
    "crates/shader-builder",
]
default-members = ["crates/shader-builder"]

[patch.crates-io]
bevy-pbr-rust = { path = "crates/bevy-pbr-rust" }
shader-util = { path = "../shared/shader-util" }
bevy-rust-gpu-macros = { path = "crates/bevy-rust-gpu-macros" }
